# 三维数组切片详解：从困惑到清晰

## 学习目标
1. 理解三维数组的结构和坐标系统
2. 掌握三维数组的3个轴的含义
3. 学会各种三维数组切片操作
4. 通过图像处理实例加深理解

## 为什么学习三维数组切片？
- **图像处理**：RGB图像是高×宽×颜色通道的三维数组
- **视频处理**：时间×高×宽的三维数组
- **科学计算**：温度场、流场等多维数据
- **深度学习**：批次×高×宽×通道的多维张量


In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# 设置中文字体和样式
plt.rcParams["font.sans-serif"] = ["SimHei", "Arial Unicode MS"]
plt.rcParams["axes.unicode_minus"] = False

print("📦 所需库导入完成")
print("🔧 准备开始三维数组切片之旅！")

📦 所需库导入完成
🔧 准备开始三维数组切片之旅！


## 1. 三维数组的基本概念

### 🤔 你的困惑是对的！
你说得对："三维数组不是由一个个二维数组嵌套的吗？"

**是的！** 三维数组确实是由多个二维数组"堆叠"而成的。我们可以这样理解：

- **一维数组**：一条线上的点 `[1, 2, 3, 4]`
- **二维数组**：一个平面上的表格（行×列）
- **三维数组**：多个二维数组堆叠成的"立方体"

### 📚 从书本的角度理解
想象一本书：
- **页数（深度）**：第几页 → **轴0 (axis=0)**
- **行数（高度）**：第几行 → **轴1 (axis=1)** 
- **列数（宽度）**：第几个字 → **轴2 (axis=2)**


In [2]:
# 创建一个简单的三维数组来理解结构
# 形状：(3, 4, 5) = (深度, 高度, 宽度) = (页数, 行数, 列数)

# 方法1：直接创建
arr_3d = np.arange(60).reshape(3, 4, 5)

print("🔍 三维数组的基本信息：")
print(f"形状 (shape): {arr_3d.shape}")
print(f"维度数 (ndim): {arr_3d.ndim}")
print(f"元素总数 (size): {arr_3d.size}")
print(f"数据类型 (dtype): {arr_3d.dtype}")

print("\n📖 完整的三维数组：")
print(arr_3d)

print("\n🔍 让我们分解这个三维数组：")
print("这个数组有3页，每页4行5列")

for i in range(3):
    print(f"\n📄 第{i}页 (axis=0, index={i}):")
    print(arr_3d[i])  # 这就是第i个二维数组

🔍 三维数组的基本信息：
形状 (shape): (3, 4, 5)
维度数 (ndim): 3
元素总数 (size): 60
数据类型 (dtype): int64

📖 完整的三维数组：
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

🔍 让我们分解这个三维数组：
这个数组有3页，每页4行5列

📄 第0页 (axis=0, index=0):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

📄 第1页 (axis=0, index=1):
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]

📄 第2页 (axis=0, index=2):
[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


## 2. 三个轴的详细解释

### 🎯 关键理解：轴的编号和含义

在numpy中，三维数组的轴编号是：
- **axis=0（轴0）**：深度轴，控制"哪一层/页"
- **axis=1（轴1）**：行轴，控制"哪一行" 
- **axis=2（轴2）**：列轴，控制"哪一列"

### 🌟 为什么第三个轴叫"深度轴"？
这是一个约定俗成的叫法：
1. **从数学角度**：Z轴通常表示深度/高度
2. **从存储角度**：axis=0是最外层的索引
3. **从可视化角度**：想象多个二维图片叠在一起

### 📐 坐标系统：
```
形状 (3, 4, 5) 表示：
├── axis=0: 3个"页面"（深度方向）
├── axis=1: 4行（垂直方向）  
└── axis=2: 5列（水平方向）
```


In [ ]:
# 可视化三维数组的结构
def visualize_3d_array_structure():
    """可视化三维数组的轴和索引"""
    
    fig = plt.figure(figsize=(15, 10))
    
    # 创建一个小的三维数组用于演示
    demo_array = np.arange(24).reshape(2, 3, 4)
    
    # 绘制每一层
    for i in range(2):
        ax = fig.add_subplot(2, 3, i*3 + 1)
        im = ax.imshow(demo_array[i], cmap='viridis', alpha=0.8)
        ax.set_title(f'第{i}层 (axis=0, index={i})')
        ax.set_xlabel('axis=2 (列)')
        ax.set_ylabel('axis=1 (行)')
        
        # 添加数值标注
        for row in range(3):
            for col in range(4):
                ax.text(col, row, f'{demo_array[i, row, col]}', 
                       ha='center', va='center', color='white', fontsize=10)
    
    # 绘制轴的说明图
    ax_explain = fig.add_subplot(2, 3, (1, 6))
    ax_explain.text(0.1, 0.8, '三维数组坐标系统:', fontsize=16, fontweight='bold')
    ax_explain.text(0.1, 0.7, '• axis=0 (深度): 选择哪一层', fontsize=12, color='red')
    ax_explain.text(0.1, 0.6, '• axis=1 (行): 选择哪一行', fontsize=12, color='green') 
    ax_explain.text(0.1, 0.5, '• axis=2 (列): 选择哪一列', fontsize=12, color='blue')
    ax_explain.text(0.1, 0.3, f'数组形状: {demo_array.shape}', fontsize=12)
    ax_explain.text(0.1, 0.2, '(深度, 行数, 列数)', fontsize=12, style='italic')
    ax_explain.set_xlim(0, 1)
    ax_explain.set_ylim(0, 1)
    ax_explain.axis('off')
    
    plt.tight_layout()
    plt.show()
    
    return demo_array

demo_array = visualize_3d_array_structure()
print(f"演示数组形状: {demo_array.shape}")
print(f"演示数组内容:\n{demo_array}")


## 3. 三维数组切片的基本语法

### 🎨 切片语法格式：
```python
array[axis0_slice, axis1_slice, axis2_slice]
array[深度切片, 行切片, 列切片]
```

### 📝 切片规则：
- **单个索引**：`arr[1, 2, 3]` → 获取单个元素
- **范围切片**：`arr[0:2, 1:3, :]` → 获取范围
- **省略部分**：`arr[0]` → 等价于 `arr[0, :, :]`
- **负数索引**：`arr[-1]` → 最后一层
- **步长切片**：`arr[::2, 1::2, :]` → 每隔一个取值


In [3]:
# 使用我们之前创建的三维数组进行切片演示
print("🔬 原始三维数组形状:", arr_3d.shape)
print("原始数组第0层:\n", arr_3d[0])

print("\n" + "=" * 50)
print("📚 各种切片操作演示:")
print("=" * 50)

# 1. 单层切片（选择特定深度）
print("\n1️⃣ 深度轴切片 - 选择特定层:")
layer_0 = arr_3d[0]  # 第0层，等价于 arr_3d[0, :, :]
layer_1 = arr_3d[1]  # 第1层
print(f"第0层形状: {layer_0.shape}")
print(f"第0层内容:\n{layer_0}")

# 2. 单个元素访问
print("\n2️⃣ 单个元素访问:")
element = arr_3d[1, 2, 3]  # 第1层，第2行，第3列
print(f"arr_3d[1, 2, 3] = {element}")

# 3. 行切片（在特定层选择特定行）
print("\n3️⃣ 行切片:")
row_slice = arr_3d[0, 1, :]  # 第0层，第1行，所有列
print(f"第0层第1行: {row_slice}")
print(f"形状: {row_slice.shape}")

# 4. 列切片（在特定层选择特定列）
print("\n4️⃣ 列切片:")
col_slice = arr_3d[0, :, 2]  # 第0层，所有行，第2列
print(f"第0层第2列: {col_slice}")
print(f"形状: {col_slice.shape}")

# 5. 多层切片
print("\n5️⃣ 多层切片:")
multi_layer = arr_3d[0:2]  # 前两层
print(f"前两层形状: {multi_layer.shape}")
print(f"前两层内容:\n{multi_layer}")

🔬 原始三维数组形状: (3, 4, 5)
原始数组第0层:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

📚 各种切片操作演示:

1️⃣ 深度轴切片 - 选择特定层:
第0层形状: (4, 5)
第0层内容:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

2️⃣ 单个元素访问:
arr_3d[1, 2, 3] = 33

3️⃣ 行切片:
第0层第1行: [5 6 7 8 9]
形状: (5,)

4️⃣ 列切片:
第0层第2列: [ 2  7 12 17]
形状: (4,)

5️⃣ 多层切片:
前两层形状: (2, 4, 5)
前两层内容:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [4]:
# 更复杂的切片操作
print("🎯 高级切片操作:")
print("=" * 40)

# 6. 区域切片（选择一个立方体区域）
print("\n6️⃣ 立方体区域切片:")
cube_slice = arr_3d[0:2, 1:3, 2:4]  # 深度0-1，行1-2，列2-3
print(f"区域切片形状: {cube_slice.shape}")
print(f"区域切片内容:\n{cube_slice}")

# 7. 步长切片
print("\n7️⃣ 步长切片:")
step_slice = arr_3d[::2, ::2, ::2]  # 每隔一个取值
print(f"步长切片形状: {step_slice.shape}")
print(f"步长切片内容:\n{step_slice}")

# 8. 负索引
print("\n8️⃣ 负索引:")
last_layer = arr_3d[-1]  # 最后一层
print(f"最后一层:\n{last_layer}")

# 9. 混合切片
print("\n9️⃣ 混合切片:")
mixed_slice = arr_3d[1, :2, -2:]  # 第1层，前2行，后2列
print(f"混合切片形状: {mixed_slice.shape}")
print(f"混合切片内容:\n{mixed_slice}")

# 10. 布尔索引
print("\n🔟 布尔索引:")
mask = arr_3d > 30
filtered = arr_3d[mask]
print(f"大于30的元素个数: {len(filtered)}")
print(f"前10个大于30的元素: {filtered[:10]}")

🎯 高级切片操作:

6️⃣ 立方体区域切片:
区域切片形状: (2, 2, 2)
区域切片内容:
[[[ 7  8]
  [12 13]]

 [[27 28]
  [32 33]]]

7️⃣ 步长切片:
步长切片形状: (2, 2, 3)
步长切片内容:
[[[ 0  2  4]
  [10 12 14]]

 [[40 42 44]
  [50 52 54]]]

8️⃣ 负索引:
最后一层:
[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]

9️⃣ 混合切片:
混合切片形状: (2, 2)
混合切片内容:
[[23 24]
 [28 29]]

🔟 布尔索引:
大于30的元素个数: 29
前10个大于30的元素: [31 32 33 34 35 36 37 38 39 40]


## 4. 实战案例：RGB图像处理

### 🖼️ 图像就是三维数组！
在图像处理中，一张彩色图片就是一个三维数组：
- **axis=0（高度）**：图片的行数
- **axis=1（宽度）**：图片的列数  
- **axis=2（通道）**：颜色通道（R, G, B）

**注意**：在图像处理中，axis的含义与我们前面的例子略有不同！


In [ ]:
# 创建一个模拟的RGB图像
def create_sample_image():
    """创建一个彩色的示例图像"""
    height, width = 100, 150
    
    # 创建渐变图像
    r_channel = np.linspace(0, 255, height*width).reshape(height, width)
    g_channel = np.linspace(255, 0, height*width).reshape(height, width)
    b_channel = np.full((height, width), 128)  # 固定的蓝色值
    
    # 合并三个通道
    image = np.stack([r_channel, g_channel, b_channel], axis=2)
    return image.astype(np.uint8)

# 创建示例图像
sample_image = create_sample_image()

print("🖼️ 示例图像信息:")
print(f"图像形状: {sample_image.shape}")
print(f"数据类型: {sample_image.dtype}")
print(f"像素值范围: {sample_image.min()} ~ {sample_image.max()}")

# 可视化原始图像和各个通道
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# 显示原始图像
axes[0, 0].imshow(sample_image)
axes[0, 0].set_title('原始RGB图像')
axes[0, 0].axis('off')

# 显示各个颜色通道
channels = ['Red', 'Green', 'Blue']
colors = ['Reds', 'Greens', 'Blues']

for i, (channel_name, colormap) in enumerate(zip(channels, colors)):
    row, col = (0, 1) if i == 0 else (1, i-1)
    axes[row, col].imshow(sample_image[:, :, i], cmap=colormap)
    axes[row, col].set_title(f'{channel_name} 通道 (axis=2, index={i})')
    axes[row, col].axis('off')

plt.tight_layout()
plt.show()

print(f"\n🔍 图像数组的详细信息:")
print(f"R通道形状: {sample_image[:, :, 0].shape}")
print(f"G通道形状: {sample_image[:, :, 1].shape}")
print(f"B通道形状: {sample_image[:, :, 2].shape}")


In [ ]:
# 图像切片操作演示
print("📸 图像切片操作实战:")
print("="*40)

# 1. 提取图像区域（ROI - Region of Interest）
print("\n1️⃣ 提取图像区域:")
roi = sample_image[20:80, 50:120, :]  # 提取中间区域
print(f"原图形状: {sample_image.shape}")
print(f"ROI形状: {roi.shape}")

# 2. 分离颜色通道
print("\n2️⃣ 分离颜色通道:")
red_channel = sample_image[:, :, 0]    # 红色通道
green_channel = sample_image[:, :, 1]  # 绿色通道
blue_channel = sample_image[:, :, 2]   # 蓝色通道

print(f"红色通道形状: {red_channel.shape}")

# 3. 创建单色图像
print("\n3️⃣ 创建单色图像:")
# 只保留红色通道，其他设为0
red_only = sample_image.copy()
red_only[:, :, 1] = 0  # 绿色通道置零
red_only[:, :, 2] = 0  # 蓝色通道置零

# 4. 图像翻转
print("\n4️⃣ 图像变换:")
flipped_horizontal = sample_image[:, ::-1, :]  # 水平翻转
flipped_vertical = sample_image[::-1, :, :]    # 垂直翻转

# 5. 图像降采样
print("\n5️⃣ 图像降采样:")
downsampled = sample_image[::2, ::2, :]  # 隔行隔列采样
print(f"降采样后形状: {downsampled.shape}")

# 可视化各种切片结果
fig, axes = plt.subplots(3, 3, figsize=(15, 12))
axes = axes.flatten()

images = [
    (sample_image, "原始图像"),
    (roi, "ROI区域"),
    (red_channel, "红色通道"),
    (green_channel, "绿色通道"), 
    (blue_channel, "蓝色通道"),
    (red_only, "只保留红色"),
    (flipped_horizontal, "水平翻转"),
    (flipped_vertical, "垂直翻转"),
    (downsampled, "降采样")
]

for i, (img, title) in enumerate(images):
    if len(img.shape) == 2:  # 灰度图像
        axes[i].imshow(img, cmap='gray')
    else:  # 彩色图像
        axes[i].imshow(img)
    axes[i].set_title(title)
    axes[i].axis('off')

plt.tight_layout()
plt.show()


## 5. 深入理解：不同领域的三维数组

### 🔄 轴的含义因应用而异
虽然都是三维数组，但在不同领域中，轴的含义是不同的：

| 应用领域 | axis=0 | axis=1 | axis=2 | 形状示例 |
|---------|--------|--------|--------|----------|
| **数学/通用** | 深度 | 行 | 列 | (深度, 行, 列) |
| **图像处理** | 高度 | 宽度 | 通道 | (H, W, C) |
| **视频处理** | 时间 | 高度 | 宽度 | (T, H, W) |
| **科学数据** | Z坐标 | Y坐标 | X坐标 | (Z, Y, X) |
| **深度学习** | 批次 | 高度 | 宽度 | (N, H, W) |


In [ ]:
# 演示不同领域的三维数组实例
print("🌍 不同领域的三维数组实例:")
print("="*50)

# 1. 科学数据：3D温度场
print("\n1️⃣ 科学数据 - 3D温度场:")
# 模拟一个3D空间中的温度分布 (Z, Y, X)
z_size, y_size, x_size = 5, 8, 10
temperature_field = np.random.normal(20, 5, (z_size, y_size, x_size))  # 平均温度20度

print(f"温度场形状: {temperature_field.shape} (Z, Y, X)")
print(f"温度范围: {temperature_field.min():.1f}°C ~ {temperature_field.max():.1f}°C")

# 提取某个高度层的温度分布
z_layer = temperature_field[2, :, :]  # 第2层的温度分布
print(f"第2层(Z=2)温度分布形状: {z_layer.shape}")

# 2. 视频数据：时间序列图像
print("\n2️⃣ 视频数据 - 时间序列:")
# 模拟视频帧 (时间, 高度, 宽度)
frames, height, width = 10, 64, 64
video_data = np.random.randint(0, 255, (frames, height, width), dtype=np.uint8)

print(f"视频数据形状: {video_data.shape} (时间, 高度, 宽度)")
print(f"总帧数: {frames}, 每帧尺寸: {height}×{width}")

# 提取第5帧
frame_5 = video_data[5, :, :]
print(f"第5帧形状: {frame_5.shape}")

# 3. 深度学习：批量图像数据
print("\n3️⃣ 深度学习 - 批量数据:")
# 模拟一个小批量的灰度图像 (批次, 高度, 宽度)
batch_size, img_h, img_w = 4, 32, 32
batch_images = np.random.rand(batch_size, img_h, img_w)

print(f"批量图像形状: {batch_images.shape} (批次, 高度, 宽度)")
print(f"批次大小: {batch_size}, 每张图片: {img_h}×{img_w}")

# 提取批次中的第一张图片
first_image = batch_images[0, :, :]
print(f"第一张图片形状: {first_image.shape}")

# 可视化这些不同类型的数据
fig, axes = plt.subplots(2, 3, figsize=(15, 10))

# 温度场可视化
im1 = axes[0, 0].imshow(z_layer, cmap='coolwarm', aspect='auto')
axes[0, 0].set_title('温度场 Z=2层')
axes[0, 0].set_xlabel('X坐标')
axes[0, 0].set_ylabel('Y坐标')
plt.colorbar(im1, ax=axes[0, 0], shrink=0.8)

# 视频帧可视化
axes[0, 1].imshow(frame_5, cmap='gray')
axes[0, 1].set_title('视频第5帧')
axes[0, 1].axis('off')

# 批量图像可视化
axes[0, 2].imshow(first_image, cmap='viridis')
axes[0, 2].set_title('批次中第一张图片')
axes[0, 2].axis('off')

# 下排显示切片操作示例
# 温度场的垂直切片
vertical_slice = temperature_field[:, 4, :]  # Y=4的垂直切片
im2 = axes[1, 0].imshow(vertical_slice, cmap='coolwarm', aspect='auto')
axes[1, 0].set_title('温度场垂直切片 (Y=4)')
axes[1, 0].set_xlabel('X坐标')
axes[1, 0].set_ylabel('Z坐标')
plt.colorbar(im2, ax=axes[1, 0], shrink=0.8)

# 视频时间切片
time_slice = video_data[:, 32, 32]  # 中心像素的时间变化
axes[1, 1].plot(time_slice, marker='o')
axes[1, 1].set_title('中心像素时间变化')
axes[1, 1].set_xlabel('时间帧')
axes[1, 1].set_ylabel('像素值')
axes[1, 1].grid(True)

# 批量数据的平均图像
mean_image = batch_images.mean(axis=0)  # 沿批次维度求平均
axes[1, 2].imshow(mean_image, cmap='viridis')
axes[1, 2].set_title('批次平均图像')
axes[1, 2].axis('off')

plt.tight_layout()
plt.show()


## 6. 常见错误和陷阱

### ❌ 初学者常犯的错误

1. **轴的顺序混淆**
   ```python
   # 错误理解
   arr[x, y, z]  # 以为是 (x, y, z) 坐标
   
   # 正确理解  
   arr[axis0, axis1, axis2]  # 按照轴的编号顺序
   ```

2. **图像处理中的轴混淆**
   ```python
   # OpenCV格式: (高度, 宽度, 通道)
   image = cv2.imread('image.jpg')  # shape: (H, W, C)
   
   # 有些库使用: (通道, 高度, 宽度)  
   tensor = torch.tensor(image).permute(2, 0, 1)  # shape: (C, H, W)
   ```

3. **切片结果维度丢失**
   ```python
   arr_3d = np.arange(60).reshape(3, 4, 5)
   
   # 这会降维
   single_element = arr_3d[0, 1, 2]  # 标量
   single_row = arr_3d[0, 1, :]     # 1D数组
   
   # 保持维度
   single_element_3d = arr_3d[0:1, 1:2, 2:3]  # 仍然是3D
   ```


In [ ]:
# 演示常见错误和正确做法
print("⚠️ 常见错误演示:")
print("="*40)

# 创建示例数组
test_array = np.arange(60).reshape(3, 4, 5)
print(f"测试数组形状: {test_array.shape}")

print("\n1️⃣ 维度丢失问题:")
# 错误做法 - 维度会丢失
wrong_slice = test_array[0, 1, :]  # 结果是1D
print(f"错误切片 test_array[0, 1, :] 形状: {wrong_slice.shape}")
print(f"结果: {wrong_slice}")

# 正确做法 - 保持维度
correct_slice = test_array[0:1, 1:2, :]  # 结果仍是3D
print(f"\n正确切片 test_array[0:1, 1:2, :] 形状: {correct_slice.shape}")
print(f"结果:\n{correct_slice}")

print("\n2️⃣ 轴顺序混淆:")
# 很多人以为 [x, y, z] 对应笛卡尔坐标
# 但实际上是 [axis0, axis1, axis2]
print("数组[1, 2, 3]的含义:")
print("- 不是坐标(x=1, y=2, z=3)")  
print("- 而是: axis0=1, axis1=2, axis2=3")
print(f"- 即: 第1层, 第2行, 第3列 = {test_array[1, 2, 3]}")

print("\n3️⃣ 图像处理中的混淆:")
# 创建一个RGB图像
rgb_image = np.random.randint(0, 255, (100, 150, 3), dtype=np.uint8)
print(f"RGB图像形状: {rgb_image.shape} = (高度, 宽度, 通道)")

# 正确的通道提取
red_channel = rgb_image[:, :, 0]
print(f"红色通道形状: {red_channel.shape}")

# 常见的错误理解
print("\n❌ 常见错误理解:")
print("认为 rgb_image[x, y, z] 是坐标(x,y,z)处的值")
print("✅ 正确理解:")  
print("rgb_image[row, col, channel] 是第row行、第col列、第channel通道的值")

print("\n4️⃣ 内存布局理解:")
# numpy数组的内存布局是行优先(C-style)
print("三维数组在内存中的布局:")
small_array = np.arange(24).reshape(2, 3, 4)
print(f"数组形状: {small_array.shape}")
print("内存中的顺序:")
print("第0层 -> 第1层")
print("每层内: 第0行 -> 第1行 -> 第2行") 
print("每行内: 第0列 -> 第1列 -> 第2列 -> 第3列")
print(f"展平后: {small_array.flatten()}")

# 可视化内存布局
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# 显示数组结构
for i in range(2):
    ax = axes[i]
    im = ax.imshow(small_array[i], cmap='viridis', alpha=0.8)
    ax.set_title(f'第{i}层')
    
    # 添加内存顺序标注
    for row in range(3):
        for col in range(4):
            value = small_array[i, row, col]
            memory_idx = i * 12 + row * 4 + col  # 在内存中的位置
            ax.text(col, row, f'{value}\n({memory_idx})', 
                   ha='center', va='center', color='white', fontsize=8)

# 显示内存布局示意图
ax = axes[2]
memory_layout = small_array.flatten().reshape(6, 4)
im = ax.imshow(memory_layout, cmap='plasma')
ax.set_title('内存布局 (6×4 重新排列)')
ax.set_xlabel('内存地址递增方向 →')

# 添加数值标注
for i in range(6):
    for j in range(4):
        value = memory_layout[i, j]
        ax.text(j, i, f'{value}', ha='center', va='center', 
               color='white', fontsize=10)

plt.tight_layout()
plt.show()


## 7. 实战练习

### 🎯 练习题目
让我们通过一些实际问题来巩固三维数组切片知识！


In [ ]:
# 实战练习
print("🎯 三维数组切片实战练习")
print("="*50)

# 创建练习用的数据
np.random.seed(42)  # 固定随机种子，确保结果可重现

# 练习1：RGB图像操作
print("\n📸 练习1: RGB图像处理")
print("-" * 30)

# 创建一个模拟的RGB图像 (128x128x3)
image_rgb = np.random.randint(0, 255, (128, 128, 3), dtype=np.uint8)
print(f"原始图像形状: {image_rgb.shape}")

# 任务1.1: 提取绿色通道
green_channel = image_rgb[:, :, 1]
print(f"绿色通道形状: {green_channel.shape}")

# 任务1.2: 提取图像的左上角64x64区域
top_left = image_rgb[:64, :64, :]
print(f"左上角区域形状: {top_left.shape}")

# 任务1.3: 创建只有红色的图像
red_only_image = image_rgb.copy()
red_only_image[:, :, 1] = 0  # 绿色通道置零
red_only_image[:, :, 2] = 0  # 蓝色通道置零

# 任务1.4: 图像下采样 (每隔一个像素取样)
downsampled = image_rgb[::2, ::2, :]
print(f"下采样后形状: {downsampled.shape}")

# 练习2：视频数据处理
print("\n🎬 练习2: 视频数据处理")
print("-" * 30)

# 创建模拟视频数据 (30帧, 64x64像素)
video_frames = np.random.randint(0, 255, (30, 64, 64), dtype=np.uint8)
print(f"视频数据形状: {video_frames.shape}")

# 任务2.1: 提取第10-20帧
clip = video_frames[10:21, :, :]
print(f"视频片段形状: {clip.shape}")

# 任务2.2: 提取所有帧的中心16x16区域
center_start = 24  # 64//2 - 8
center_end = 40    # 64//2 + 8
center_regions = video_frames[:, center_start:center_end, center_start:center_end]
print(f"中心区域形状: {center_regions.shape}")

# 任务2.3: 提取每5帧的数据
every_5th_frame = video_frames[::5, :, :]
print(f"每5帧取样形状: {every_5th_frame.shape}")

# 练习3：科学数据分析
print("\n🔬 练习3: 3D科学数据")
print("-" * 30)

# 创建3D温度场数据 (10x20x30)
temperature_3d = np.random.normal(25, 10, (10, 20, 30))  # 温度数据
print(f"3D温度场形状: {temperature_3d.shape} (Z, Y, X)")

# 任务3.1: 提取表面层(z=0)的温度分布
surface_temp = temperature_3d[0, :, :]
print(f"表面温度分布形状: {surface_temp.shape}")

# 任务3.2: 提取垂直剖面(y=10)
vertical_section = temperature_3d[:, 10, :]
print(f"垂直剖面形状: {vertical_section.shape}")

# 任务3.3: 提取立方体子区域 (z:2-8, y:5-15, x:10-25)
cube_region = temperature_3d[2:8, 5:15, 10:25]
print(f"立方体区域形状: {cube_region.shape}")

# 任务3.4: 计算每层的平均温度
layer_means = temperature_3d.mean(axis=(1, 2))  # 沿Y和X轴求平均
print(f"每层平均温度: {layer_means.shape}")
print(f"前5层平均温度: {layer_means[:5]}")

# 可视化练习结果
fig, axes = plt.subplots(3, 4, figsize=(16, 12))

# 第一行：图像处理结果
axes[0, 0].imshow(image_rgb[:64, :64, :])
axes[0, 0].set_title('原图(左上角)')
axes[0, 0].axis('off')

axes[0, 1].imshow(green_channel, cmap='gray')
axes[0, 1].set_title('绿色通道')
axes[0, 1].axis('off')

axes[0, 2].imshow(red_only_image[:64, :64, :])
axes[0, 2].set_title('只保留红色')
axes[0, 2].axis('off')

axes[0, 3].imshow(downsampled[:32, :32, :])
axes[0, 3].set_title('下采样')
axes[0, 3].axis('off')

# 第二行：视频处理结果
axes[1, 0].imshow(video_frames[0], cmap='gray')
axes[1, 0].set_title('第0帧')
axes[1, 0].axis('off')

axes[1, 1].imshow(video_frames[15], cmap='gray')
axes[1, 1].set_title('第15帧')
axes[1, 1].axis('off')

axes[1, 2].imshow(center_regions[0], cmap='gray')
axes[1, 2].set_title('中心区域(第0帧)')
axes[1, 2].axis('off')

# 显示时间序列
pixel_timeline = video_frames[:, 32, 32]  # 中心像素的时间变化
axes[1, 3].plot(pixel_timeline)
axes[1, 3].set_title('中心像素时间变化')
axes[1, 3].set_xlabel('帧数')
axes[1, 3].set_ylabel('像素值')
axes[1, 3].grid(True)

# 第三行：科学数据结果
im1 = axes[2, 0].imshow(surface_temp, cmap='coolwarm')
axes[2, 0].set_title('表面温度分布')
plt.colorbar(im1, ax=axes[2, 0], shrink=0.8)

im2 = axes[2, 1].imshow(vertical_section, cmap='coolwarm')
axes[2, 1].set_title('垂直剖面(Y=10)')
axes[2, 1].set_xlabel('X')
axes[2, 1].set_ylabel('Z')
plt.colorbar(im2, ax=axes[2, 1], shrink=0.8)

im3 = axes[2, 2].imshow(cube_region[3, :, :], cmap='coolwarm')  # 显示立方体中的一层
axes[2, 2].set_title('立方体区域(Z=5层)')
plt.colorbar(im3, ax=axes[2, 2], shrink=0.8)

axes[2, 3].plot(layer_means, marker='o')
axes[2, 3].set_title('每层平均温度')
axes[2, 3].set_xlabel('层数(Z)')
axes[2, 3].set_ylabel('温度(°C)')
axes[2, 3].grid(True)

plt.tight_layout()
plt.show()

print("\n✅ 练习完成！你已经掌握了三维数组的基本切片操作。")
